services:
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USER}
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017
    depends_on:
      - db